name: "Run system tests"
description: "Run system tests for the specified module"

inputs:
  module_name:
    description: "module name to run system tests"
    required: true

runs:
  using: "composite"
  steps:
    - name: checkout the repository
      uses: actions/checkout@v2
