name: first

on: push

jobs:
  job1:
    name: First job
    strategy:
      matrix:
        node: ["nidigital", "1", "2", "3", "4", "5", "6", "7", "8", "10"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: step one
        uses: actions/checkout@v2

      - name: run system test1
        uses: SukruthGrandhiNI/githubactions@master
        with:
          who-to-greet: ${{ matrix.node }}
