name: first

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest

    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: run system test1
        uses: ./.github/actions/run_module_system_tests
        with:
          module_name: nidigital
