name: first

on:
  push: #TBD
    paths-ignore:
      - CHANGELOG.md
      - CONTRIBUTING.md
      - .gitattributes
      - LICENSE
      - VERSION
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  job1:
    name: First job
    strategy:
      matrix:
        module_name: [ "nidigital", "nitclk", "nifgen", "nidcpower", "nidmm", "niscope", "nimodinst", "nise", "niswitch"]
        os: ["self-hosted", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: system_tests_win32
        uses: SukruthGrandhiNI/githubactions@master
        with:
          module_name: ${{ matrix.node }}
